### ISSUE TITLE
Gigabyte GC-AQC113C Not visible

### ISSUE THREAD

**Issue by frommelt5** [CaseySJ/Aquantia-macOS-Patches#1]
With these patches in macOS Ventura 13.3.1 on a AMD Ryzen System the 10gbe Card Gigabyte GC-AQC113C is not shown in the device manager? Of course opencore is used.  Is it a problem with the last macOS update or is more needed than just the patches?
Thanks for your work, your knowhow is amazing

**Comment by CaseySJ** [comment]
@frommelt5,

To use GC-AQC113C in macOS Monterey and newer, we must spoof the `device-id` to `0x94C0`. We can do this via `DeviceProperties` or through a custom SSDT.

On my Z390 Designare, I use
[SSDT-AQUANTIA-AQC113C-RP21.aml.zip](https://github.com/CaseySJ/Aquantia-macOS-Patches/files/11365092/SSDT-AQUANTIA-AQC113C-RP21.aml.zip). But the PCI path in this file must be modified for the motherboard **and** slot you're using.

**Comment by CaseySJ** [comment]
Requirements for Gigabyte GC-AQC113C:

1. Enable kernel quirk `ForceAquantiaEthernet`
2. Install and enable either  *Set 1* or *Set 2* patches from this repository
3. Spoof device ID to `0x94C0`

On Intel systems with more than 16GB memory and a supported iGPU enabled in macOS, it's also necessary to enable this quirk in OpenCore 0.9.2 and newer:

- `DisableIoMapperMapping`
