### ISSUE TITLE
USB restriction patches for MacOS11 to 14 systems, Check XhciPortLimit and then all USB ports can be used, breaking the limit of 15 ports

### ISSUE THREAD

**Issue by Wate321** [CaseySJ/Aquantia-macOS-Patches#2]
USB restriction patches for MacOS11 to 14 systems, Check XhciPortLimit and then all USB ports can be used, breaking the limit of 15 ports
.Hope to integrate this patch into opencore
[Wate-macOS-XhciPortLimit-Patch.plist.zip](https://github.com/CaseySJ/Aquantia-macOS-Patches/files/11710331/Wate-macOS-XhciPortLimit-Patch.plist.zip)
https://github.com/WaTeZhuangJiDingZhi/wate

**Comment by CaseySJ** [comment]
Hi, this looks very interesting. I'll examine it tomorrow and provide more feedback.

**Comment by CaseySJ** [comment]
@WaTeZhuangJiDingZhi 

Quick question: Should (a) Count, (b) Limit, and (c) Skip all be zero for the Ventura/Sonoma patch?

![Screenshot 2023-06-11 at 9 53 37 AM](https://github.com/CaseySJ/Aquantia-macOS-Patches/assets/48335376/63262421-a1e0-49a4-b34c-55f89a9a0561)

**Comment by CaseySJ** [comment]
I've tested the patch on Ventura and Sonoma using my Gigabyte Z390 Designare. It does work and makes more than 15 ports available!

One of the ports, HS14 (Internal Bluetooth), does not get enabled. Not sure if this is an issue to be fixed, but it is something to be aware of.

**Sonoma** (HS14 is missing):

![Screenshot 2023-06-11 at 10 04 20 AM](https://github.com/CaseySJ/Aquantia-macOS-Patches/assets/48335376/4c2217f5-1586-4b87-8463-93772e3a02fa)

**Ventura** (same HS14 missing):

![Screenshot 2023-06-11 at 10 08 42 AM](https://github.com/CaseySJ/Aquantia-macOS-Patches/assets/48335376/260a2852-4a60-4454-a2c4-3a07c107b737)

**Comment by Wate321** [comment]
Of course, you still need to cancel the original USB port patch and re-inject USBInjectAll.kext or XHCI-unsupported.kext (up to Z690) USBToolBox.kext+UTBMap.kext (for 700 and AMD)

Sorry Sonoma Apple changed the patch, I need to re-search the new 14 patch, so the above patch is completely applicable to 11-13, Sonoma I need to search again, I am busy recently. An x86 assembler guy could help me just fine.

**Comment by CaseySJ** [comment]
> Of course, you still need to cancel the original USB port patch and re-inject USBInjectAll.kext or XHCI-unsupported.kext (up to Z690) USBToolBox.kext+UTBMap.kext (for 700 and AMD)
> 

My tests yesterday were done (a) **without** port map and (b) **without** USBInjectAll.

But today I re-ran the test (a) **without** port map, but (b) **with** USBInjectAll. In Ventura, this _correctly enabled all USB ports_.

> Sorry Sonoma Apple changed the patch, I need to re-search the new 14 patch, so the above patch is completely applicable to 11-13, Sonoma I need to search again, I am busy recently. An x86 assembler guy could help me just fine.

Correct -- the patch does not seem to work currently in Sonoma.
